version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: groupassignment-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: jensen
      MYSQL_PASSWORD: devops25
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: Europe/Stockholm
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 6

  adminer:
    image: adminer:latest
    container_name: groupassignment-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  db_data:
